// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.ASSETS_JPG_IMAGE_DEFAULT_JPG.preview}
  static const String ASSETS_JPG_IMAGE_DEFAULT_JPG =
      'assets/jpg/image_default.jpg';

  /// {@macro assets_generator.ASSETS_JPG_IMG_CARD_CCCD_PNG.preview}
  static const String ASSETS_JPG_IMG_CARD_CCCD_PNG =
      'assets/jpg/img_card_cccd.png';

  /// {@macro assets_generator.ASSETS_JPG_IMG_MAIL_PNG.preview}
  static const String ASSETS_JPG_IMG_MAIL_PNG = 'assets/jpg/img_mail.png';

  static const String ASSETS_LOCALES_VI_VN_JSON = 'assets/locales/vi_VN.json';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ACC_EKYC_SVG.preview}
  static const String ASSETS_SVG_ICON_ACC_EKYC_SVG =
      'assets/svg/icon_acc_ekyc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ADD_ITEM_SVG.preview}
  static const String ASSETS_SVG_ICON_ADD_ITEM_SVG =
      'assets/svg/icon_add_item.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_APPEAR_EYE_SVG.preview}
  static const String ASSETS_SVG_ICON_APPEAR_EYE_SVG =
      'assets/svg/icon_appear_eye.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_AWAIT_OCR_DATA_SVG.preview}
  static const String ASSETS_SVG_ICON_AWAIT_OCR_DATA_SVG =
      'assets/svg/icon_await_ocr_data.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BACK_SVG.preview}
  static const String ASSETS_SVG_ICON_BACK_SVG = 'assets/svg/icon_back.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BANNER_HOME_SVG.preview}
  static const String ASSETS_SVG_ICON_BANNER_HOME_SVG =
      'assets/svg/icon_banner_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BELL_SVG.preview}
  static const String ASSETS_SVG_ICON_BELL_SVG = 'assets/svg/icon_bell.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BIRTHDAY_SVG.preview}
  static const String ASSETS_SVG_ICON_BIRTHDAY_SVG =
      'assets/svg/icon_birthday.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BORDER_TOP_LEFT_SVG.preview}
  static const String ASSETS_SVG_ICON_BORDER_TOP_LEFT_SVG =
      'assets/svg/icon_border_top_left.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_BORDER_TOP_LEFT_CAP_SVG.preview}
  static const String ASSETS_SVG_ICON_BORDER_TOP_LEFT_CAP_SVG =
      'assets/svg/icon_border_top_left_cap.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CANCEL_SVG.preview}
  static const String ASSETS_SVG_ICON_CANCEL_SVG = 'assets/svg/icon_cancel.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CANLENDAR_CARD_SVG.preview}
  static const String ASSETS_SVG_ICON_CANLENDAR_CARD_SVG =
      'assets/svg/icon_canlendar_card.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CARD_CCCD_SVG.preview}
  static const String ASSETS_SVG_ICON_CARD_CCCD_SVG =
      'assets/svg/icon_card_cccd.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CARD_INFO_SVG.preview}
  static const String ASSETS_SVG_ICON_CARD_INFO_SVG =
      'assets/svg/icon_card_info.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CHECKMARK_SVG.preview}
  static const String ASSETS_SVG_ICON_CHECKMARK_SVG =
      'assets/svg/icon_checkmark.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CLOSE_SVG.preview}
  static const String ASSETS_SVG_ICON_CLOSE_SVG = 'assets/svg/icon_close.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CONTRACT_SVG.preview}
  static const String ASSETS_SVG_ICON_CONTRACT_SVG =
      'assets/svg/icon_contract.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_LEFT_DOWN_PNG.preview}
  static const String ASSETS_SVG_ICON_CORNER_LEFT_DOWN_PNG =
      'assets/svg/icon_corner_left_down.png';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_LEFT_UP_PNG.preview}
  static const String ASSETS_SVG_ICON_CORNER_LEFT_UP_PNG =
      'assets/svg/icon_corner_left_up.png';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_RIGHT_DOWN_PNG.preview}
  static const String ASSETS_SVG_ICON_CORNER_RIGHT_DOWN_PNG =
      'assets/svg/icon_corner_right_down.png';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CORNER_RIGHT_UP_PNG.preview}
  static const String ASSETS_SVG_ICON_CORNER_RIGHT_UP_PNG =
      'assets/svg/icon_corner_right_up.png';

  /// {@macro assets_generator.ASSETS_SVG_ICON_CREATE_FOLDER_SVG.preview}
  static const String ASSETS_SVG_ICON_CREATE_FOLDER_SVG =
      'assets/svg/icon_create_folder.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_DELETE_SVG.preview}
  static const String ASSETS_SVG_ICON_DELETE_SVG = 'assets/svg/icon_delete.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_DIRECTION_SVG.preview}
  static const String ASSETS_SVG_ICON_DIRECTION_SVG =
      'assets/svg/icon_direction.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_EMAIL_SVG.preview}
  static const String ASSETS_SVG_ICON_EMAIL_SVG = 'assets/svg/icon_email.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_BETWEEN_SVG.preview}
  static const String ASSETS_SVG_ICON_FACE_BETWEEN_SVG =
      'assets/svg/icon_face_between.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_BLINK_SVG.preview}
  static const String ASSETS_SVG_ICON_FACE_BLINK_SVG =
      'assets/svg/icon_face_blink.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_DOWN_SVG.preview}
  static const String ASSETS_SVG_ICON_FACE_DOWN_SVG =
      'assets/svg/icon_face_down.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_LEFT_SVG.preview}
  static const String ASSETS_SVG_ICON_FACE_LEFT_SVG =
      'assets/svg/icon_face_left.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_RIGHT_SVG.preview}
  static const String ASSETS_SVG_ICON_FACE_RIGHT_SVG =
      'assets/svg/icon_face_right.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_SMILE_SVG.preview}
  static const String ASSETS_SVG_ICON_FACE_SMILE_SVG =
      'assets/svg/icon_face_smile.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FACE_UP_SVG.preview}
  static const String ASSETS_SVG_ICON_FACE_UP_SVG =
      'assets/svg/icon_face_up.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FLASH_SVG.preview}
  static const String ASSETS_SVG_ICON_FLASH_SVG = 'assets/svg/icon_flash.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_FLASH_OFF_SVG.preview}
  static const String ASSETS_SVG_ICON_FLASH_OFF_SVG =
      'assets/svg/icon_flash_off.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_GENDER_SVG.preview}
  static const String ASSETS_SVG_ICON_GENDER_SVG = 'assets/svg/icon_gender.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_GLOBE_SVG.preview}
  static const String ASSETS_SVG_ICON_GLOBE_SVG = 'assets/svg/icon_globe.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_HIDDEN_EYE_SVG.preview}
  static const String ASSETS_SVG_ICON_HIDDEN_EYE_SVG =
      'assets/svg/icon_hidden_eye.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_INSTRUCT_LIVE_NESS_SVG.preview}
  static const String ASSETS_SVG_ICON_INSTRUCT_LIVE_NESS_SVG =
      'assets/svg/icon_instruct_live_ness.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_BUY_HOME_SVG.preview}
  static const String ASSETS_SVG_ICON_ITEM_BUY_HOME_SVG =
      'assets/svg/icon_item_buy_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_EXTEND_HOME_HOME_SVG.preview}
  static const String ASSETS_SVG_ICON_ITEM_EXTEND_HOME_HOME_SVG =
      'assets/svg/icon_item_extend_home_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_INFO_HOME_SVG.preview}
  static const String ASSETS_SVG_ICON_ITEM_INFO_HOME_SVG =
      'assets/svg/icon_item_info_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_KYC_SVG.preview}
  static const String ASSETS_SVG_ICON_ITEM_KYC_SVG =
      'assets/svg/icon_item_kyc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_MISSION_HOME_SVG.preview}
  static const String ASSETS_SVG_ICON_ITEM_MISSION_HOME_SVG =
      'assets/svg/icon_item_mission_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_ITEM_RECALL_HOME_SVG.preview}
  static const String ASSETS_SVG_ICON_ITEM_RECALL_HOME_SVG =
      'assets/svg/icon_item_recall_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_KYC_SVG.preview}
  static const String ASSETS_SVG_ICON_KYC_SVG = 'assets/svg/icon_kyc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_SVG.preview}
  static const String ASSETS_SVG_ICON_LIST_SVG = 'assets/svg/icon_list.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_CTS_SVG.preview}
  static const String ASSETS_SVG_ICON_LIST_CTS_SVG =
      'assets/svg/icon_list_cts.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_DOCUMENT_ITEM_HOME_SVG.preview}
  static const String ASSETS_SVG_ICON_LIST_DOCUMENT_ITEM_HOME_SVG =
      'assets/svg/icon_list_document_item_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_DOCUMENT_NOT_CONFIRM_ITEM_HOME_SVG.preview}
  static const String ASSETS_SVG_ICON_LIST_DOCUMENT_NOT_CONFIRM_ITEM_HOME_SVG =
      'assets/svg/icon_list_document_not_confirm_item_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIST_NULL_SVG.preview}
  static const String ASSETS_SVG_ICON_LIST_NULL_SVG =
      'assets/svg/icon_list_null.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LIVE_NESS_SVG.preview}
  static const String ASSETS_SVG_ICON_LIVE_NESS_SVG =
      'assets/svg/icon_live_ness.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOAD_ERR_SVG.preview}
  static const String ASSETS_SVG_ICON_LOAD_ERR_SVG =
      'assets/svg/icon_load_err.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOCK_SVG.preview}
  static const String ASSETS_SVG_ICON_LOCK_SVG = 'assets/svg/icon_lock.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_LOGOUT_SVG.preview}
  static const String ASSETS_SVG_ICON_LOGOUT_SVG = 'assets/svg/icon_logout.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_MAP_SVG.preview}
  static const String ASSETS_SVG_ICON_MAP_SVG = 'assets/svg/icon_map.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_MORE_HOME_SVG.preview}
  static const String ASSETS_SVG_ICON_MORE_HOME_SVG =
      'assets/svg/icon_more_home.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NATIONALITY_SVG.preview}
  static const String ASSETS_SVG_ICON_NATIONALITY_SVG =
      'assets/svg/icon_nationality.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_SVG.preview}
  static const String ASSETS_SVG_ICON_NFC_SVG = 'assets/svg/icon_nfc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_CONNECT_SVG.preview}
  static const String ASSETS_SVG_ICON_NFC_CONNECT_SVG =
      'assets/svg/icon_nfc_connect.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_HOME_TOWN_SVG.preview}
  static const String ASSETS_SVG_ICON_NFC_HOME_TOWN_SVG =
      'assets/svg/icon_nfc_home_town.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_IDENTIFYING_SIGNS_SVG.preview}
  static const String ASSETS_SVG_ICON_NFC_IDENTIFYING_SIGNS_SVG =
      'assets/svg/icon_nfc_identifying_signs.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NFC_NATION_SVG.preview}
  static const String ASSETS_SVG_ICON_NFC_NATION_SVG =
      'assets/svg/icon_nfc_nation.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NO_SUPPORT_NFC_SVG.preview}
  static const String ASSETS_SVG_ICON_NO_SUPPORT_NFC_SVG =
      'assets/svg/icon_no_support_nfc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTI_BELL_SVG.preview}
  static const String ASSETS_SVG_ICON_NOTI_BELL_SVG =
      'assets/svg/icon_noti_bell.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTI_SUCCESS_SVG.preview}
  static const String ASSETS_SVG_ICON_NOTI_SUCCESS_SVG =
      'assets/svg/icon_noti_success.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NOTIFICATION_SVG.preview}
  static const String ASSETS_SVG_ICON_NOTIFICATION_SVG =
      'assets/svg/icon_notification.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_NUMBER_PHONE_SVG.preview}
  static const String ASSETS_SVG_ICON_NUMBER_PHONE_SVG =
      'assets/svg/icon_number_phone.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_PACKAGE_SVG.preview}
  static const String ASSETS_SVG_ICON_PACKAGE_SVG =
      'assets/svg/icon_package.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_PACKAGE_CARD_SVG.preview}
  static const String ASSETS_SVG_ICON_PACKAGE_CARD_SVG =
      'assets/svg/icon_package_card.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_REGISTER_KYC_SVG.preview}
  static const String ASSETS_SVG_ICON_REGISTER_KYC_SVG =
      'assets/svg/icon_register_kyc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SCAN_NFC_SVG.preview}
  static const String ASSETS_SVG_ICON_SCAN_NFC_SVG =
      'assets/svg/icon_scan_nfc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SERVICE_CA_SVG.preview}
  static const String ASSETS_SVG_ICON_SERVICE_CA_SVG =
      'assets/svg/icon_service_ca.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SUCCESS_SVG.preview}
  static const String ASSETS_SVG_ICON_SUCCESS_SVG =
      'assets/svg/icon_success.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_SUPPORT_NFC_SVG.preview}
  static const String ASSETS_SVG_ICON_SUPPORT_NFC_SVG =
      'assets/svg/icon_support_nfc.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_TAG_SVG.preview}
  static const String ASSETS_SVG_ICON_TAG_SVG = 'assets/svg/icon_tag.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_TAKE_PICTURE_SVG.preview}
  static const String ASSETS_SVG_ICON_TAKE_PICTURE_SVG =
      'assets/svg/icon_take_picture.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_TELEPHONE_SVG.preview}
  static const String ASSETS_SVG_ICON_TELEPHONE_SVG =
      'assets/svg/icon_telephone.svg';

  /// {@macro assets_generator.ASSETS_SVG_ICON_USER_NAME_CARD_SVG.preview}
  static const String ASSETS_SVG_ICON_USER_NAME_CARD_SVG =
      'assets/svg/icon_user_name_card.svg';
}
