name: two_id_c06verify
description: A new Flutter project.

_internal_variables_:
  - &syncfusion_ver "23.2.4"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependency_overrides:
  dio: ^5.4.2+1

dependencies:
  app_settings: ^5.1.1
  asn1lib: ^1.5.3
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  device_info_plus: 9.1.2
  dio: ^5.4.2+1
  dio_log_sds:
    git:
      url: https://github.com/HVLoc/dio_log_sds.git
      ref: master
  dmrtd:
    git:
      url: https://github.com/HVLoc/dmrtd
      ref: master
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_multi_formatter: ^2.12.4
  flutter_pdfview: ^1.2.7
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  fluttertoast: ^8.2.5
  get: ^4.6.6
  google_fonts: 6.1.0
  google_mlkit_face_detection: ^0.9.0
  hive: ^2.2.3
  just_audio: ^0.9.38
  loading_overlay_pro: ^2.1.1
  logger: ^2.2.0
  mobile_scanner: ^3.5.2
  nfc_manager: ^3.4.0
  package_info_plus: ^4.2.0
  percent_indicator: ^4.2.3
  permission_handler: ^8.1.6
  pull_to_refresh: ^2.0.0
  screenshot: ^2.3.0
  sds_assets_generator:
    git:
      url: https://github.com/toannmdev/sds_assets_generator.git
      ref: master
  signature: ^5.4.1
  syncfusion_flutter_core: 23.2.4
  syncfusion_flutter_datepicker: *syncfusion_ver
  syncfusion_flutter_pdfviewer: *syncfusion_ver
  image: ^4.1.3
  flutter_nfc_kit: 3.4.2
  url_launcher: ^6.2.1
  youtube_player_flutter: 8.1.2
  local_auth: ^2.2.0
  image_picker: ^1.0.5

#  gallery_saver: ^2.1.1
dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: ^3.0.2
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  #  fonts:
  #    - family: NunitoSans
  #      fonts:
  #        - asset: assets/fonts/NunitoSans-Regular.ttf
  #          weight: 400
  #        - asset: assets/fonts/NunitoSans-SemiBold.ttf
  #          weight: 600
  #        - asset: assets/fonts/NunitoSans-Bold.ttf
  #          weight: 700
  #        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
  #          weight: 800
  # To add assets to your application, add an assets section, like this:
  assets:

  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by SoftDreams Developer
  # **************************************************************************

    - assets/jpg/icon_banner_login.png
    - assets/jpg/icon_faceid.png
    - assets/jpg/icon_fingerprint.png
    - assets/jpg/image_banner.png
    - assets/jpg/image_default.jpg
    - assets/jpg/img_card_cccd.png
    - assets/jpg/img_mail.png
    - assets/locales/vi_VN.json
    - assets/svg/icon_acc_ekyc.svg
    - assets/svg/icon_add_item.svg
    - assets/svg/icon_appear_eye.svg
    - assets/svg/icon_authentication.svg
    - assets/svg/icon_await_ocr_data.svg
    - assets/svg/icon_back.svg
    - assets/svg/icon_banner_home.svg
    - assets/svg/icon_bell.svg
    - assets/svg/icon_birthday.svg
    - assets/svg/icon_border_top_left.svg
    - assets/svg/icon_border_top_left_cap.svg
    - assets/svg/icon_cancel.svg
    - assets/svg/icon_canlendar_card.svg
    - assets/svg/icon_card_cccd.svg
    - assets/svg/icon_card_info.svg
    - assets/svg/icon_checkmark.svg
    - assets/svg/icon_close.svg
    - assets/svg/icon_contract.svg
    - assets/svg/icon_corner_left_down.png
    - assets/svg/icon_corner_left_up.png
    - assets/svg/icon_corner_right_down.png
    - assets/svg/icon_corner_right_up.png
    - assets/svg/icon_create_folder.svg
    - assets/svg/icon_delete.svg
    - assets/svg/icon_direction.svg
    - assets/svg/icon_done.svg
    - assets/svg/icon_email.svg
    - assets/svg/icon_face_between.svg
    - assets/svg/icon_face_blink.svg
    - assets/svg/icon_face_down.svg
    - assets/svg/icon_face_left.svg
    - assets/svg/icon_face_right.svg
    - assets/svg/icon_face_smile.svg
    - assets/svg/icon_face_up.svg
    - assets/svg/icon_flash.svg
    - assets/svg/icon_flash_off.svg
    - assets/svg/icon_gender.svg
    - assets/svg/icon_globe.svg
    - assets/svg/icon_hidden_eye.svg
    - assets/svg/icon_home_authentication.svg
    - assets/svg/icon_home_authentication_focus.svg
    - assets/svg/icon_home_list_user.svg
    - assets/svg/icon_home_list_user_focus.svg
    - assets/svg/icon_home_list_user_focus_focus.svg
    - assets/svg/icon_home_other.svg
    - assets/svg/icon_home_service_package.svg
    - assets/svg/icon_home_service_package_focus.svg
    - assets/svg/icon_instruct_live_ness.svg
    - assets/svg/icon_item_buy_home.svg
    - assets/svg/icon_item_extend_home_home.svg
    - assets/svg/icon_item_info_home.svg
    - assets/svg/icon_item_kyc.svg
    - assets/svg/icon_item_mission_home.svg
    - assets/svg/icon_item_recall_home.svg
    - assets/svg/icon_kyc.svg
    - assets/svg/icon_kyc_login.svg
    - assets/svg/icon_kyc_small.svg
    - assets/svg/icon_list.svg
    - assets/svg/icon_list_cts.svg
    - assets/svg/icon_list_document_item_home.svg
    - assets/svg/icon_list_document_not_confirm_item_home.svg
    - assets/svg/icon_list_null.svg
    - assets/svg/icon_list_user.svg
    - assets/svg/icon_live_ness.svg
    - assets/svg/icon_load_err.svg
    - assets/svg/icon_lock.svg
    - assets/svg/icon_logout.svg
    - assets/svg/icon_map.svg
    - assets/svg/icon_more_home.svg
    - assets/svg/icon_nationality.svg
    - assets/svg/icon_nfc.svg
    - assets/svg/icon_nfc_connect.svg
    - assets/svg/icon_nfc_home_town.svg
    - assets/svg/icon_nfc_identifying_signs.svg
    - assets/svg/icon_nfc_nation.svg
    - assets/svg/icon_no_support_nfc.svg
    - assets/svg/icon_noti_bell.svg
    - assets/svg/icon_noti_success.svg
    - assets/svg/icon_notification.svg
    - assets/svg/icon_number_phone.svg
    - assets/svg/icon_package.svg
    - assets/svg/icon_package_card.svg
    - assets/svg/icon_pass.svg
    - assets/svg/icon_register_kyc.svg
    - assets/svg/icon_scan_nfc.svg
    - assets/svg/icon_service_ca.svg
    - assets/svg/icon_service_package.svg
    - assets/svg/icon_success.svg
    - assets/svg/icon_support.svg
    - assets/svg/icon_support_nfc.svg
    - assets/svg/icon_tag.svg
    - assets/svg/icon_take_picture.svg
    - assets/svg/icon_telephone.svg
    - assets/svg/icon_user.svg
    - assets/svg/icon_user_name_card.svg

  # assets end